/**
 * Copyrighht 2021 to present, Antonio Malcolm.
 * All rights reserved.
 *
 * This source code file is a part of protoreaction (A.K.A., "protoReaction").
 *
 * This source code is licensed under the BSD 3-Clause license,
 * and is subject to the terms of the BSD 3-Clause license,
 * found in the LICENSE file, in the root directory of this project.
 * If a copy of the BSD 3-Clause license cannot be found,
 * as part of this project, you can obtain one, at:
 * https://opensource.org/licenses/BSD-3-Clause
 */

'use strict';

const AppInfo = require('./AppInfo');
const CurrentVarValues = require('./CurrentVarValues');

/**
 * Private Fileds...
 */
const currentEnviron = CurrentVarValues.ENVIRON;
const currentWorkspace = CurrentVarValues.WORKSPACE;

/**
 * Exposed Fields...
 */

/**
 * Base relative path names...
 */
const APP_ROOT = AppInfo.APP_PACKAGE_JSON_LOCATION.replace('/package.json', '');
const ASSET_RELATIVE = 'asset';
const AUDIO_RELATIVE = 'audio';
const BUILD_RELATIVE = 'build';
const CACHE_RELATIVE = 'cache';
const CONFIG_RELATIVE = 'config';
const CONSTANT_RELATIVE = 'constant';
const CSS_RELATIVE = 'css';
const DIST_RELATIVE = 'dist';
const EXCEPTION_RELATIVE = 'exception';
const FONT_RELATIVE = 'font';
const HTML_RELATIVE = 'html';
const IMAGE_RELATIVE = 'image';
const JS_RELATIVE = 'js';
const NODE_MODULES_RELATIVE = 'node_modules';
const REPORT_RELATIVE = 'report';
const SERVER_RELATIVE = 'server';
const SRC_RELATIVE = 'src';
const STYLE_RELATIVE = 'style';
const TEMPLATE_RELATIVE = 'template';
const TEST_RELATIVE = 'test';
const UTIL_RELATIVE = 'util';
const VIDEO_RELATIVE = 'video';
const WORKSPACES_RELATIVE = 'workspaces';

const BUILD_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}/${currentWorkspace}/${BUILD_RELATIVE}`;
const BUILD_CACHE_ABSOLUTE = `${BUILD_ABSOLUTE}/${CACHE_RELATIVE}/${currentEnviron}`;
const BUILD_DIST_RELATIVE = `${WORKSPACES_RELATIVE}/${currentWorkspace}/${BUILD_RELATIVE}/${DIST_RELATIVE}/${currentEnviron}`;
const BUILD_DIST_ABSOLUTE = `${APP_ROOT}/${BUILD_DIST_RELATIVE}`;

const CONFIG_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${CONFIG_RELATIVE}`;
const CONFIG_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}/${currentWorkspace}/${CONFIG_RELATIVE}`;
const CONSTANT_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${CONSTANT_RELATIVE}`;

const EXCEPTION_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${EXCEPTION_RELATIVE}`;

const NODE_MODULES_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${NODE_MODULES_RELATIVE}`;
const NODE_MODULES_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${currentWorkspace}/${NODE_MODULES_RELATIVE}`;

const REGEX_DIRECTORY_NAME_NODE_MODULES = /[\\/]node_modules[\\/]/;
const REGEX_DIRECTORY_NAME_NODE_MODULES_PKG = /[\\/]node_modules[\\/](.*?)([\\/]|$)/;

const SRC_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${SRC_RELATIVE}`;
const SRC_CURRENT_WORKSPACE_RELATIVE = `${WORKSPACES_RELATIVE}/${currentWorkspace}/${SRC_RELATIVE}`;
const SRC_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${SRC_CURRENT_WORKSPACE_RELATIVE}`;

const SERVER_ADDRESS_LOCALHOST = 'localhost';
const SERVER_PORT = '3001';

const SERVER_FILES_RELATIVE = 'srv';
const SERVER_FILES_MMRY_RELATIVE = 'mmry';
const SERVER_ASSETS_AVAIL_RELATIVE = 'available';
const SERVER_FILES_ABSOLUTE = `${APP_ROOT}/${SERVER_RELATIVE}/${SERVER_FILES_RELATIVE}`;
const SERVER_FILES_MMRY_ABSOLUTE = `${APP_ROOT}/${SERVER_RELATIVE}/mmry`;

const TEMPLATE_CSS_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${TEMPLATE_RELATIVE}/${CSS_RELATIVE}`;
const TEMPLATE_CSS_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}/${currentWorkspace}/${TEMPLATE_RELATIVE}/${CSS_RELATIVE}`;
const TEMPLATE_HTML_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${TEMPLATE_RELATIVE}/${HTML_RELATIVE}`;
const TEMPLATE_HTML_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}/${currentWorkspace}/${TEMPLATE_RELATIVE}/${HTML_RELATIVE}`;
const TEMPLATE_JS_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${TEMPLATE_RELATIVE}/${JS_RELATIVE}`;
const TEMPLATE_JS_CURRENT_WORKSPACE_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}/${currentWorkspace}/${TEMPLATE_RELATIVE}/${JS_RELATIVE}`;

const TEST_ABSOLUTE = `${APP_ROOT}/${TEST_RELATIVE}`;
const TEST_CACHE_RELATIVE = `${TEST_RELATIVE}/${CACHE_RELATIVE}`;
const TEST_CACHE_ABSOLUTE = `${APP_ROOT}/${TEST_CACHE_RELATIVE}`;
const TEST_OUTPUT_RELATIVE = `${TEST_RELATIVE}/output`;
const TEST_OUTPUT_ABSOLUTE = `${APP_ROOT}/${TEST_OUTPUT_RELATIVE}`;
const TEST_SPEC_RELATIVE = `${TEST_RELATIVE}/spec`;
const TEST_SPEC_ABSOLUTE = `${APP_ROOT}/${TEST_SPEC_RELATIVE}`;

const UTIL_APP_ROOT_ABSOLUTE = `${APP_ROOT}/${UTIL_RELATIVE}`;

const WORKSPACES_ABSOLUTE = `${APP_ROOT}/${WORKSPACES_RELATIVE}`;

module.exports = Object.freeze({
  APP_ROOT,
  ASSET_RELATIVE,
  AUDIO_RELATIVE,
  BUILD_CACHE_ABSOLUTE,
  BUILD_DIST_ABSOLUTE,
  BUILD_RELATIVE,
  CONFIG_APP_ROOT_ABSOLUTE,
  CONFIG_CURRENT_WORKSPACE_ABSOLUTE,
  CONSTANT_APP_ROOT_ABSOLUTE,
  DIST_RELATIVE,
  EXCEPTION_APP_ROOT_ABSOLUTE,
  FONT_RELATIVE,
  IMAGE_RELATIVE,
  NODE_MODULES_APP_ROOT_ABSOLUTE,
  NODE_MODULES_CURRENT_WORKSPACE_ABSOLUTE,
  NODE_MODULES_RELATIVE,
  REGEX_DIRECTORY_NAME_NODE_MODULES,
  REGEX_DIRECTORY_NAME_NODE_MODULES_PKG,
  REPORT_RELATIVE,
  SERVER_ADDRESS_LOCALHOST,
  SERVER_ASSETS_AVAIL_RELATIVE,
  SERVER_FILES_ABSOLUTE,
  SERVER_FILES_MMRY_ABSOLUTE,
  SERVER_FILES_MMRY_RELATIVE,
  SERVER_FILES_RELATIVE,
  SERVER_RELATIVE,
  SERVER_PORT,
  SRC_APP_ROOT_ABSOLUTE,
  SRC_CURRENT_WORKSPACE_ABSOLUTE,
  SRC_CURRENT_WORKSPACE_RELATIVE,
  SRC_RELATIVE,
  STYLE_RELATIVE,
  TEMPLATE_CSS_APP_ROOT_ABSOLUTE,
  TEMPLATE_CSS_CURRENT_WORKSPACE_ABSOLUTE,
  TEMPLATE_HTML_APP_ROOT_ABSOLUTE,
  TEMPLATE_HTML_CURRENT_WORKSPACE_ABSOLUTE,
  TEMPLATE_JS_APP_ROOT_ABSOLUTE,
  TEMPLATE_JS_CURRENT_WORKSPACE_ABSOLUTE,
  TEST_ABSOLUTE,
  TEST_CACHE_ABSOLUTE,
  TEST_CACHE_RELATIVE,
  TEST_OUTPUT_ABSOLUTE,
  TEST_OUTPUT_RELATIVE,
  TEST_RELATIVE,
  TEST_SPEC_ABSOLUTE,
  TEST_SPEC_RELATIVE,
  UTIL_APP_ROOT_ABSOLUTE,
  VIDEO_RELATIVE,
  WORKSPACES_ABSOLUTE,
  WORKSPACES_RELATIVE
});
